export const colors = [
  { color: "White", colorCode: "#FFFFFF", image: null },
  { color: "Black", colorCode: "#000000", image: null },
  { color: "Silver", colorCode: "#C0C0C0", image: null },
  { color: "Gray", colorCode: "#808080", image: null },
  { color: "Red", colorCode: "#FF0000", image: null },
  { color: "Gold", colorCode: "#FFD700", image: null },
  { color: "Graphite", colorCode: "#383838", image: null },
  { color: "Green", colorCode: "#00FF00", image: null },
  { color: "Orange", colorCode: "#FFA500", image: null },
  { color: "Blue", colorCode: "#0000FF", image: null },
  { color: "Yellow", colorCode: "#FFFF00", image: null },
  { color: "Purple", colorCode: "#800080", image: null },
  { color: "Pink", colorCode: "#FFC0CB", image: null },
  { color: "Brown", colorCode: "#A52A2A", image: null },
  { color: "Beige", colorCode: "#F5F5DC", image: null },
  { color: "Cyan", colorCode: "#00FFFF", image: null },
  { color: "Magenta", colorCode: "#FF00FF", image: null },
  { color: "Lime", colorCode: "#00FF00", image: null },
  { color: "Olive", colorCode: "#808000", image: null },
  { color: "Maroon", colorCode: "#800000", image: null },
  { color: "Navy", colorCode: "#000080", image: null },
  { color: "Teal", colorCode: "#008080", image: null },
  { color: "Turquoise", colorCode: "#40E0D0", image: null },
  { color: "Violet", colorCode: "#EE82EE", image: null },
  { color: "Indigo", colorCode: "#4B0082", image: null },
  { color: "Lavender", colorCode: "#E6E6FA", image: null },
  { color: "Salmon", colorCode: "#FA8072", image: null },
  { color: "Coral", colorCode: "#FF7F50", image: null },
  { color: "Khaki", colorCode: "#F0E68C", image: null },
  { color: "Plum", colorCode: "#DDA0DD", image: null },
  { color: "Orchid", colorCode: "#DA70D6", image: null },
  { color: "Chocolate", colorCode: "#D2691E", image: null },
  { color: "Tomato", colorCode: "#FF6347", image: null },
  { color: "Mint", colorCode: "#98FF98", image: null },
  { color: "Azure", colorCode: "#F0FFFF", image: null },
  { color: "Peach", colorCode: "#FFE5B4", image: null },
  { color: "Ivory", colorCode: "#FFFFF0", image: null },
  { color: "Mauve", colorCode: "#E0B0FF", image: null },
  { color: "Crimson", colorCode: "#DC143C", image: null },
  { color: "Sapphire", colorCode: "#0F52BA", image: null },
  { color: "Amber", colorCode: "#FFBF00", image: null },
  { color: "Bronze", colorCode: "#CD7F32", image: null },
  { color: "Copper", colorCode: "#B87333", image: null },
  { color: "Emerald", colorCode: "#50C878", image: null },
  { color: "Ruby", colorCode: "#E0115F", image: null },
  { color: "Amethyst", colorCode: "#9966CC", image: null },
  { color: "Pearl", colorCode: "#EAE0C8", image: null },
  { color: "Jade", colorCode: "#00A86B", image: null },
  { color: "Sand", colorCode: "#C2B280", image: null },
  { color: "Rose", colorCode: "#FF007F", image: null },
  { color: "Lemon", colorCode: "#FFF700", image: null },
  { color: "Mustard", colorCode: "#FFDB58", image: null },
  { color: "Berry", colorCode: "#8A2BE2", image: null },
  { color: "Sky Blue", colorCode: "#87CEEB", image: null },
  { color: "Forest Green", colorCode: "#228B22", image: null },
  { color: "Seafoam", colorCode: "#93DFB8", image: null },
  { color: "Burgundy", colorCode: "#800020", image: null },
  { color: "Slate", colorCode: "#708090", image: null },
  { color: "Charcoal", colorCode: "#36454F", image: null },
  { color: "Aqua", colorCode: "#00FFFF", image: null },
  { color: "Fuchsia", colorCode: "#FF00FF", image: null },
  { color: "Lilac", colorCode: "#C8A2C8", image: null },
  { color: "Periwinkle", colorCode: "#CCCCFF", image: null },
  { color: "Rust", colorCode: "#B7410E", image: null },
  { color: "Mahogany", colorCode: "#C04000", image: null },
  { color: "Tangerine", colorCode: "#F28500", image: null },
  { color: "Midnight Blue", colorCode: "#191970", image: null },
  { color: "Blush", colorCode: "#DE5D83", image: null },
  { color: "Flamingo", colorCode: "#FC8EAC", image: null },
  { color: "Chartreuse", colorCode: "#7FFF00", image: null },
  { color: "Cobalt", colorCode: "#0047AB", image: null },
  { color: "Mulberry", colorCode: "#C54B8C", image: null },
  { color: "Canary", colorCode: "#FFFF99", image: null },
  { color: "Carmine", colorCode: "#960018", image: null },
  { color: "Denim", colorCode: "#1560BD", image: null },
  { color: "Heliotrope", colorCode: "#DF73FF", image: null },
  { color: "Cerulean", colorCode: "#007BA7", image: null },
  { color: "Sepia", colorCode: "#704214", image: null },
  { color: "Saffron", colorCode: "#F4C430", image: null },
  { color: "Almond", colorCode: "#EFDECD", image: null },
  { color: "Electric Blue", colorCode: "#7DF9FF", image: null },
  { color: "Onyx", colorCode: "#353839", image: null },
  { color: "Vanilla", colorCode: "#F3E5AB", image: null },
  { color: "Cerise", colorCode: "#DE3163", image: null },
  { color: "Sangria", colorCode: "#92000A", image: null },
  { color: "Ebony", colorCode: "#555D50", image: null },
  { color: "Jet", colorCode: "#343434", image: null },
  { color: "Coral Pink", colorCode: "#F88379", image: null },
  { color: "Electric Green", colorCode: "#00FF00", image: null },
  { color: "Mint Green", colorCode: "#98FF98", image: null },
  { color: "Steel Blue", colorCode: "#4682B4", image: null },
  { color: "Zaffre", colorCode: "#0014A8", image: null },
  { color: "Capri", colorCode: "#00BFFF", image: null },
  { color: "Emerald Green", colorCode: "#50C878", image: null },
  { color: "Brass", colorCode: "#B5A642", image: null },
  { color: "Rosewood", colorCode: "#65000B", image: null },
  { color: "Sunset Orange", colorCode: "#FD5E53", image: null },
  { color: "Sunflower", colorCode: "#FFDA03", image: null },
  { color: "Blizzard Blue", colorCode: "#ACE5EE", image: null },
  { color: "Desert Sand", colorCode: "#EDC9AF", image: null },
  { color: "Lava", colorCode: "#CF1020", image: null },
  { color: "Cardinal", colorCode: "#C41E3A", image: null },
  { color: "Coral Red", colorCode: "#FF4040", image: null },
  { color: "Royal Blue", colorCode: "#4169E1", image: null },
  { color: "Lemon Yellow", colorCode: "#FFF44F", image: null },
  { color: "Neon Green", colorCode: "#39FF14", image: null },
  { color: "Sky Magenta", colorCode: "#CF71AF", image: null },
  { color: "Goldenrod", colorCode: "#DAA520", image: null },
  { color: "Olive Drab", colorCode: "#6B8E23", image: null },
  { color: "Outrageous Orange", colorCode: "#FF6E4A", image: null },
  { color: "Shocking Pink", colorCode: "#FC0FC0", image: null },
  { color: "Laser Lemon", colorCode: "#FEFE22", image: null },
  { color: "Inchworm", colorCode: "#B2EC5D", image: null },
  { color: "Screamin Green", colorCode: "#76FF7A", image: null },
  { color: "Razzmatazz", colorCode: "#E3256B", image: null },
  { color: "Outer Space", colorCode: "#414A4C", image: null },
  { color: "Spring Green", colorCode: "#00FF7F", image: null },
  { color: "Fern Green", colorCode: "#4F7942", image: null },
  { color: "Crimson Red", colorCode: "#990000", image: null },
  { color: "Peach Puff", colorCode: "#FFDAB9", image: null },
  { color: "Firebrick", colorCode: "#B22222", image: null },
  { color: "Hot Pink", colorCode: "#FF69B4", image: null },
  { color: "Lawn Green", colorCode: "#7CFC00", image: null },
  { color: "Dark Orange", colorCode: "#FF8C00", image: null },
  { color: "Light Sea Green", colorCode: "#20B2AA", image: null },
  { color: "Dodger Blue", colorCode: "#1E90FF", image: null },
  { color: "Persian Green", colorCode: "#00A693", image: null },
  { color: "Mango Tango", colorCode: "#FF8243", image: null },
  { color: "Dark Magenta", colorCode: "#8B008B", image: null },
  { color: "Deep Pink", colorCode: "#FF1493", image: null },
  { color: "Light Coral", colorCode: "#F08080", image: null },
];
